# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function to calculate log likelihood using cpp
#' @param ances vector of ancestors
#' @param states_R numericmatrix of states
#' @param forTime_R numericmatrix of phylogeny information
#' @param lambdas vector of lambdas
#' @param mus vector of mus
#' @param Q numericmatrix with transition rates
#' @param num_threads
#' @export
calThruNodes_cpp <- function(ances, states_R, forTime_R, lambdas, mus, Q, num_threads) {
    .Call(`_secsseCPP_calThruNodes_cpp`, ances, states_R, forTime_R, lambdas, mus, Q, num_threads)
}

#' function to calculate log likelihood using cpp
#' @param ances vector of ancestors
#' @param states_R numericmatrix of states
#' @param forTime_R numericmatrix of phylogeny information
#' @param lambdas vector of lambdas
#' @param mus vector of mus
#' @param Q numericmatrix with transition rates
#' @export
cla_calThruNodes_cpp <- function(ances, states_R, forTime_R, lambdas, mus, Q) {
    .Call(`_secsseCPP_cla_calThruNodes_cpp`, ances, states_R, forTime_R, lambdas, mus, Q)
}

